---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.web.type }}
  {{- if .Values.service.web.externalIPs }}
  externalIPs:
  {{- toYaml .Values.service.web.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.web.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.service.web.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.web.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.web.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml .Values.service.web.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  publishNotReadyAddresses: {{ .Values.service.web.publishNotReadyAddresses }}
  ports:
  - name: http
    port: {{ .Values.service.web.port }}
    protocol: TCP
    targetPort: {{ .Values.service.web.targetPort }}
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}-tcp
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.tcp.type }}
  {{- if .Values.service.tcp.externalIPs }}
  externalIPs:
  {{- toYaml .Values.service.tcp.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.tcp.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.service.tcp.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.tcp.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.tcp.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml .Values.service.tcp.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  publishNotReadyAddresses: {{ .Values.service.tcp.publishNotReadyAddresses }}
  ports:
  - name: tcp
    port: {{ .Values.service.tcp.port }}
    protocol: TCP
    targetPort: {{ .Values.service.tcp.targetPort }}
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}-udp
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.udp.type }}
  {{- if .Values.service.udp.externalIPs }}
  externalIPs:
  {{- toYaml .Values.service.udp.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.udp.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.service.udp.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.udp.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.udp.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml .Values.service.udp.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  publishNotReadyAddresses: {{ .Values.service.udp.publishNotReadyAddresses }}
  ports:
  - name: udp
    port: {{ .Values.service.udp.port }}
    protocol: UDP
    targetPort: {{ .Values.service.udp.targetPort }}
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}-discovery
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.discovery.type }}
  {{- if .Values.service.discovery.externalIPs }}
  externalIPs:
  {{- toYaml .Values.service.discovery.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.discovery.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.service.discovery.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.discovery.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.discovery.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml .Values.service.discovery.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  publishNotReadyAddresses: {{ .Values.service.discovery.publishNotReadyAddresses }}
  ports:
  - name: discovery
    port: {{ .Values.service.udp.port }}
    protocol: UDP
    targetPort: {{ .Values.service.discovery.targetPort }}
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
