apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- with .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
{{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
{{- with .Values.service.ports }}
  ports:
    - port: {{ .Values.binanceProxy.portSpot }}
      targetPort: {{ .Values.binanceProxy.portSpot }}
      protocol: TCP
      name: port-spot
    - port: {{ .Values.binanceProxy.portFutures }}
      targetPort: {{ .Values.binanceProxy.portFutures }}
      protocol: TCP
      name: port-futures
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
