---
image:
  repository: syncthing/syncthing
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
replicaCount: 1
serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  web:
    type: ClusterIP
    port: 8384
    targetPort: 8384
  tcp:
    type: ClusterIP
    port: 22000
    targetPort: 22000
    externalTrafficPolicy: Local
  udp:
    type: ClusterIP
    port: 22000
    targetPort: 22000
    externalTrafficPolicy: Local
  discovery:
    type: ClusterIP
    port: 21027
    targetPort: 21027
    externalTrafficPolicy: Local

monitoring:
  enabled: false
  serviceMonitor:
    enabled: false
    labels: {}
    honorLabels: true
    interval: 60s
    selector: {}
    namespace: {}
    scrapeTimeout: 10s
    scheme: http
    tlsConfig: {}
    relabelings: []
    # - sourceLabels: [__meta_kubernetes_pod_node_name]
    #   separator: ;
    #   regex: ^(.*)$
    #   target_label: nodename
    #   replacement: $1
    #   action: replace
    metricRelabelings: []
    # - action: keep
    #   regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
    #   sourceLabels: [__name__]
    bearerTokenFile: {}
    # (use long lived access tokens)
    bearerTokenSecret: {}
    # name:
    # key:
    # optional:
livenessProbe:
  enabled: true
  # scheme: HTTP
  periodSeconds: 60
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 6
  initialDelaySeconds: 30
readinessProbe:
  enabled: true
  # scheme: HTTP
  periodSeconds: 60
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 6
  initialDelaySeconds: 30
startupProbe:
  enabled: true
  # scheme: HTTP
  successThreshold: 1
  failureThreshold: 6

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 350m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi


nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  ## syncthing data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  ##
  ## If you want to reuse an existing claim, you can pass the name of the PVC using
  ## the existingClaim variable
  # existingClaim: your-claim
  ##
  ## If you want to use a volume on the host machine instead of a PVC:
  # hostPath: /path/to/the/config/folder
  accessMode: ReadWriteOnce
  size: 2Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  averageCPUUtilizationPercentage: 50
  averageMemoryUtilizationPercentage: 50
