apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - name: http
    port: {{ .Values.container.port }}
    targetPort: {{ .Values.container.port }}
    protocol: TCP
  selector:
    app: {{ template "app.name" . }}
  type: ClusterIP
