{{- if .Values.metrics.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "app.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - path: /metrics
      interval: {{ .Values.metrics.interval }}
      scrapeTimeout: {{ .Values.metrics.scrapeTimeout }}
      port: http
      {{- if .Values.metrics.relabelings }}
      relabelings:
        {{- toYaml .Values.metrics.relabelings | nindent 8 }}
      {{- end -}}
      {{- if .Values.metrics.metricRelabelings }}
      metricRelabelings:
        {{- toYaml .Values.metrics.metricRelabelings | nindent 8 }}
      {{- end -}}
{{- end -}}
