---
image:
  repository: louislam/uptime-kuma
  tag: ""
  pullPolicy: IfNotPresent
  PullSecrets: []

# If this option  set to false a StateFulset instead of a Deployment is used
useDeploy: false

nameOverride: ""
fullnameOverride: ""
revisionHistoryLimit: 4
hostNetwork: false

replicas: 1
updateStrategy:
  type: RollingUpdate
  # rollingUpdate:
  #   maxUnavailable: 0
  #   maxSurge: 1

serviceAccount:
  create: true
  annotations: {}
  automountServiceAccountToken: false

podAnnotations: {}
podLabels: {}

extraEnv:
  {}
#   - name: "UPTIME_KUMA_PORT"
#     value: "3001"

extraEnvSecrets:
  # This will set ${MQTT_PASSWORD} to the 'password' key from the 'mqtt' secret
  # MQTT_PASSWORD:
  #   secret: mqtt
  #   key: password

## If you'd like to provide your own Kubernetes Secret object instead of passing your values
## individually, pass in the name of a created + populated Secret.
## All secrets will be mounted as environment variables, with each key/value mapping to a
## corresponding environment variable.
extraSecretForEnvFrom: []
# - esphome-secrets

podSecurityContext: {}
  # fsGroup: 2000
  # privileged: true

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  annotations: {}
    # prometheus.io/scrape: "false"
    # prometheus.io/port: {{ .Values.service.metricsPort }}
  labels: {}
  type: ClusterIP
  externalIPs: []
  loadBalancerIP: ""
  externalTrafficPolicy: {}
  loadBalancerSourceRanges: []
  publishNotReadyAddresses: false
  httpPort: "3001"
  metricsPort: "9100"

monitoring:
  enabled: false
  serviceMonitor:
    enabled: false
    labels: {}
    honorLabels: true
    interval: 60s
    selector: {}
    namespace: {}
    scrapeTimeout: 10s
    scheme: http
    tlsConfig: {}
    relabelings: []
    # - sourceLabels: [__meta_kubernetes_pod_node_name]
    #   separator: ;
    #   regex: ^(.*)$
    #   target_label: nodename
    #   replacement: $1
    #   action: replace
    metricRelabelings: []
    # - action: keep
    #   regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
    #   sourceLabels: [__name__]
    bearerTokenFile: {}
    # (use long lived access tokens)
    bearerTokenSecret: {}
      # name:
      # key:
      # optional:

livenessProbe:
  enabled: false
  scheme: HTTP
  periodSeconds: 60
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 6
  initialDelaySeconds: 30
readinessProbe:
  enabled: false
  scheme: HTTP
  periodSeconds: 60
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 6
  initialDelaySeconds: 30

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  labels: {}
  path: /
  hosts:
    - chart-example.local
  ## Extra paths to prepend to every host configuration. This is useful when working with annotation based services.
  extraPaths: []
  # - path: /*
  #   backend:
  #     serviceName: ssl-redirect
  #     servicePort: use-annotation
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
#   requests:
#     cpu: "1"
#     memory: "256Mi"
#   limits:
#     cpu: "1"
#     memory: "512Mi"

nodeSelector: {}
affinity: {}
tolerations: []

persistence:
  enabled: false
  configstorage:
    hostPath:  {}
  pvc:
    enabled: false
    # accessModes:
    #   - {}
    # resources:
    #   requests:
    #     storage: 2Gi
    # storageClassName: ""

# Mount devices or folders from the host machine. Can be used for USB device mounting.
hostMounts: []
  # Example
  # - name: cdrw
  #   hostPath: /dev/cdrw
