{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.namespaced | ternary "RoleBinding" "ClusterRoleBinding" }}
metadata:
  name: {{ printf "%s-viewer" (include "app.fullname" .) }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .Values.namespaced | ternary "Role" "ClusterRole" }}
  name: {{ template "app.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "app.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
