---
replicaCount: {}

image:
  repository: nightshift2k/binance-proxy
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
timezone: CET

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  capabilities:
    add: ["NET_ADMIN"]

service:
  type: ClusterIP
  externalIPs: []
  loadBalancerIP: ""

  ports:
    - name: port-spot
      protocol: TCP
      targetPort: 8090
      port: 8090
    - name: port-futures
      protocol: TCP
      targetPort: 8091
      port: 8091

resources: {}
# limits:
#   memory: 0.2Gi
#   cpu: 250m
# requests:
#   memory: 0.1Gi
#   cpu: 150m

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  averageCPUUtilizationPercentage: 50
  averageMemoryUtilizationPercentage: 50

nodeSelector: {}
tolerations: []
affinity: {}

binanceProxy:
  verbose: false            # -v, --verbose
  portSpot: 8090            # -p, --port-spot
  portFutures: 8091         # -t, --port-futures
  disableFakeCandles: false # -c, --disable-fake-candles
  disableSpot: false        # -s, --disable-spot
  disableFutures: false     # -f, --disable-futures
  alwaysShowForwards: false # -a, --always-show-forwards
