apiVersion: v2
appVersion: 1.39.1
description: Zigbee Bridge via MQTT
name: zigbee2mqtt
version: 0.0.9
type: application
keywords:
  - zigbee2mqtt
  - zigbee
  - mqtt
home: https://github.com/JacekZubielik/jz-helm-charts/tree/master/charts/zigbee2mqtt
icon: https://www.zigbee2mqtt.io/images/logo.png
sources:
  - https://github.com/Koenkk/zigbee2mqtt
maintainers:
  - name: jacekzubielik
