---
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.annotations }}
  annotations:
  {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
  name: {{ template "app.fullname" . }}
  labels:
  {{- include "app.labels" . | nindent 4 }}
  {{- if .Values.service.labels }}
  {{ toYaml .Values.service.labels | indent 4 }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
