image:
  repository: esphome/esphome
  tag: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
nameOverride: ""
fullnameOverride: ""
revisionHistoryLimit: 2
hostNetwork: false
replicas: 1
strategyType: RollingUpdate
serviceAccount:
  create: true
  annotations: {}
  automountServiceAccountToken: false
podAnnotations: {}
podLabels: {}
extraEnv: {}
extraEnvSecrets:
  # This will set ${MQTT_PASSWORD} to the 'password' key from the 'mqtt' secret
  # MQTT_PASSWORD:
  #   secret: mqtt
  #   key: password
## If you'd like to provide your own Kubernetes Secret object instead of passing your values
## individually, pass in the name of a created + populated Secret.
## All secrets will be mounted as environment variables, with each key/value mapping to a
## corresponding environment variable.
extraSecretForEnvFrom: []
# - esphome-secrets
podSecurityContext:
  privileged: false
  # fsGroup: 2000
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
service:
  annotations: {}
    # prometheus.io/scrape: "false"
    # prometheus.io/port: {{ .Values.service.metricsPort }}
  labels: {}
  type: ClusterIP
  externalIPs: []
  loadBalancerIP: ""
  externalTrafficPolicy: {}
  loadBalancerSourceRanges: []
  publishNotReadyAddresses: false
  httpPort: 6052
  metricsPort: 9100
monitoring:
  enabled: false
  serviceMonitor:
    enabled: false
    labels: {}
    honorLabels: true
    interval: 60s
    selector: {}
    namespace: {}
    scrapeTimeout: 10s
    scheme: http
    tlsConfig: {}
    relabelings: []
    # - sourceLabels: [__meta_kubernetes_pod_node_name]
    #   separator: ;
    #   regex: ^(.*)$
    #   target_label: nodename
    #   replacement: $1
    #   action: replace
    metricRelabelings: []
    # - action: keep
    #   regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
    #   sourceLabels: [__name__]
    bearerTokenFile: {}
    # (use long lived access tokens)
    bearerTokenSecret: {}
      # name:
      # key:
      # optional:
livenessProbe:
  enabled: true
  scheme: HTTP
  periodSeconds: 60
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 6
  initialDelaySeconds: 30
readinessProbe:
  enabled: true
  scheme: HTTP
  periodSeconds: 60
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 6
  initialDelaySeconds: 30
ingress:
  enabled: false
  # className: ""
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_cache_bypass $http_upgrade;
      }
  hosts:
    - host: esphome.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    []
    # - secretName: letsencrypt-staging
    #   hosts:
    #     - esphome.local
resources: {}
#   requests:
#     cpu: "1"
#     memory: "256Mi"
#   limits:
#     cpu: "1"
#     memory: "512Mi"
nodeSelector:
  kubernetes.io/hostname: {}
affinity: {}
tolerations: []
persistence:
  enabled: false
  configstorage:
    hostPath: {}
  pvc:
    enabled: false
    accessModes:
      - {}
    resources:
      requests:
        storage: 2Gi
    storageClassName: ""
# Mount devices or folders from the host machine. Can be used for USB device mounting.
hostMounts: []
  # - name: zha
  #   hostPath: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_6120245D-if01-port0
