name: Release Charts

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  tag_prefix: ver

on:
  pull_request:
    branches: [master]
    types:
      - closed

  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Add dependency chart repos
        run: |
          helm repo add jz-helm-charts https://jacekzubielik.github.io/jz-helm-charts

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@protonmail.com"
          git config --global --add safe.directory /charts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add repositories
        run: |
          for dir in $(ls -d charts/*/); do
            helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
          done

      ## This is required to consider the old Circle-CI Index and to stay compatible with all the old releases.
      - name: Fetch current Chart Index
        run: |
          git checkout origin/gh-pages index.yaml        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: "true"
          CR_INDEX_PATH: "./index.yaml"